Repository bank-vaults/vault-sdk, pull requests merged in 2024-02, with the labels that each got.

#331 ci: update dependabot config
  .github/dependabot.yaml
Labels: size/S

#332 perf: add session cache to improve tls efficiency
  vault/client.go
Labels: size/XS

#337 feat: bump go and vault dep version
  .github/workflows/ci.yaml
  go.mod
  go.sum
Labels: size/XL

#340 feat: Cancel previous workflow on push
  .github/workflows/ci.yaml
Labels: size/XS
